-- Supabase Postgres schema + RLS for YA Dormitory System
-- Apply in Supabase SQL editor (in order).

-- 1) Extensions
create extension if not exists pgcrypto;

-- 2) Profiles (maps to auth.users)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text,
  email text,
  phone text,
  address text,
  emergency_contact text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end; $$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- 3) Core tables
create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  room_no text not null unique,
  floor_no int not null,
  capacity int not null default 0,
  status text not null default 'Available',
  created_at timestamptz not null default now()
);

create table if not exists public.beds (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  bed_no text not null,
  status text not null default 'Available', -- Available | Reserved | Occupied
  reserved_at timestamptz,
  created_at timestamptz not null default now(),
  unique(room_id, bed_no)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  booking_ref text unique,
  user_id uuid references public.profiles(id) on delete set null,
  bed_id bigint references public.beds(id) on delete set null,
  full_name text,
  category text,
  school_name text,
  contact_number text,
  guardian_name text,
  guardian_contact text,
  payment_method text,
  receipt_path text,
  booking_status text not null default 'Pending',
  payment_status text not null default 'Pending',
  monthly_rent numeric(10,2) not null default 0,
  current_balance numeric(10,2) not null default 0,
  move_in_date date,
  move_out_date date,
  due_date date,
  remarks text,
  created_at timestamptz not null default now()
);

create index if not exists idx_bookings_user on public.bookings(user_id);
create index if not exists idx_bookings_bed on public.bookings(bed_id);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  amount numeric(10,2) not null default 0,
  payment_method text,
  notes text,
  receipt_path text,
  paid_at timestamptz not null default now()
);

create index if not exists idx_payments_booking on public.payments(booking_id);

create table if not exists public.transfer_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  requested_floor int not null,
  requested_room_id bigint not null references public.rooms(id) on delete cascade,
  requested_bed_no text,
  reason text not null,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

create table if not exists public.request_out_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  booking_id bigint not null references public.bookings(id) on delete cascade,
  request_out_date date not null,
  reason text not null,
  status text not null default 'Pending',
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Chat tables
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  last_message text,
  updated_at timestamptz not null default now()
);

create index if not exists idx_chats_user on public.chats(user_id);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null references public.chats(id) on delete cascade,
  sender_type text not null, -- user | admin
  message text,
  file_url text,
  is_voice boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_messages_chat on public.messages(chat_id);

-- 4) Helpers: admin check
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false)
$$;

-- 5) RLS enable
alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.beds enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;
alter table public.transfer_requests enable row level security;
alter table public.request_out_requests enable row level security;
alter table public.chats enable row level security;
alter table public.messages enable row level security;

-- 6) RLS policies

-- Profiles
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
using (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update
using (auth.uid() = id or public.is_admin())
with check (auth.uid() = id or public.is_admin());

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles for insert
with check (auth.uid() = id);

-- Rooms/Beds: readable to all authenticated users; writable by admin
drop policy if exists "rooms_select_auth" on public.rooms;
create policy "rooms_select_auth"
on public.rooms for select
using (auth.role() = 'authenticated');

drop policy if exists "rooms_write_admin" on public.rooms;
create policy "rooms_write_admin"
on public.rooms for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "beds_select_auth" on public.beds;
create policy "beds_select_auth"
on public.beds for select
using (auth.role() = 'authenticated');

drop policy if exists "beds_write_admin" on public.beds;
create policy "beds_write_admin"
on public.beds for all
using (public.is_admin())
with check (public.is_admin());

-- Bookings: users see own; admin sees all
drop policy if exists "bookings_select_own_or_admin" on public.bookings;
create policy "bookings_select_own_or_admin"
on public.bookings for select
using (public.is_admin() or user_id = auth.uid());

drop policy if exists "bookings_insert_own_or_admin" on public.bookings;
create policy "bookings_insert_own_or_admin"
on public.bookings for insert
with check (public.is_admin() or user_id = auth.uid());

drop policy if exists "bookings_update_admin_or_own" on public.bookings;
create policy "bookings_update_admin_or_own"
on public.bookings for update
using (public.is_admin() or user_id = auth.uid())
with check (public.is_admin() or user_id = auth.uid());

-- Payments: user can read payments for own bookings; admin all. Inserts/updates admin only (or via server route using service key).
drop policy if exists "payments_select_own_or_admin" on public.payments;
create policy "payments_select_own_or_admin"
on public.payments for select
using (
  public.is_admin() or
  exists (select 1 from public.bookings b where b.id = payments.booking_id and b.user_id = auth.uid())
);

drop policy if exists "payments_write_admin" on public.payments;
create policy "payments_write_admin"
on public.payments for all
using (public.is_admin())
with check (public.is_admin());

-- Transfer requests: user own; admin all
drop policy if exists "transfer_select_own_or_admin" on public.transfer_requests;
create policy "transfer_select_own_or_admin"
on public.transfer_requests for select
using (public.is_admin() or user_id = auth.uid());

drop policy if exists "transfer_insert_own" on public.transfer_requests;
create policy "transfer_insert_own"
on public.transfer_requests for insert
with check (user_id = auth.uid());

drop policy if exists "transfer_update_admin" on public.transfer_requests;
create policy "transfer_update_admin"
on public.transfer_requests for update
using (public.is_admin())
with check (public.is_admin());

-- Request-out: user own; admin all
drop policy if exists "requestout_select_own_or_admin" on public.request_out_requests;
create policy "requestout_select_own_or_admin"
on public.request_out_requests for select
using (public.is_admin() or user_id = auth.uid());

drop policy if exists "requestout_insert_own" on public.request_out_requests;
create policy "requestout_insert_own"
on public.request_out_requests for insert
with check (user_id = auth.uid());

drop policy if exists "requestout_update_admin" on public.request_out_requests;
create policy "requestout_update_admin"
on public.request_out_requests for update
using (public.is_admin())
with check (public.is_admin());

-- Chats/messages
drop policy if exists "chats_select_own_or_admin" on public.chats;
create policy "chats_select_own_or_admin"
on public.chats for select
using (public.is_admin() or user_id = auth.uid());

drop policy if exists "chats_insert_own" on public.chats;
create policy "chats_insert_own"
on public.chats for insert
with check (user_id = auth.uid());

drop policy if exists "chats_update_own_or_admin" on public.chats;
create policy "chats_update_own_or_admin"
on public.chats for update
using (public.is_admin() or user_id = auth.uid())
with check (public.is_admin() or user_id = auth.uid());

drop policy if exists "messages_select_chat_participant_or_admin" on public.messages;
create policy "messages_select_chat_participant_or_admin"
on public.messages for select
using (
  public.is_admin() or
  exists (select 1 from public.chats c where c.id = messages.chat_id and c.user_id = auth.uid())
);

drop policy if exists "messages_insert_chat_participant_or_admin" on public.messages;
create policy "messages_insert_chat_participant_or_admin"
on public.messages for insert
with check (
  public.is_admin() or
  exists (select 1 from public.chats c where c.id = messages.chat_id and c.user_id = auth.uid())
);

-- 7) Consistency trigger: keep booking display fields aligned with profile (best-effort)
create or replace function public.sync_bookings_from_profile()
returns trigger language plpgsql as $$
begin
  update public.bookings
     set full_name = new.full_name,
         contact_number = new.phone
   where user_id = new.id;
  return new;
end; $$;

drop trigger if exists trg_profile_sync_bookings on public.profiles;
create trigger trg_profile_sync_bookings
after update of full_name, phone on public.profiles
for each row execute function public.sync_bookings_from_profile();

